export const CHANNEL_CREATE_UPDATE_NAME = 'CHANNEL_CREATE_UPDATE_NAME';
export const CHANNEL_CREATE_UPDATE_PASSWORD = 'CHANNEL_CREATE_UPDATE_PASSWORD';
export const CHANNEL_CREATE_UPDATE_STATUS = 'CHANNEL_CREATE_UPDATE_STATUS';
export const CHANNEL_AVAILABILITY = 'CHANNEL_AVAILABILITY';
export const CHANNEL_CREATE = 'CHANNEL_CREATE';
