module.exports = {
  container: {},
  editorStyle: {
    fontFamily: 'helvetica, Helvetica Nue',
    fontWeight: 'bold',
    fontSize: '2em',
    padding: '.05rem',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
  text: {
    fontFamily: 'helvetica, Helvetica Nue',
    fontWeight: 'bold',
    backgroundImage: 'linear-gradient(180deg, #249bff 0%, #e1f8ff 44%, #3a006b 44%, #ff57d6 100%)',
    backgroundClip: 'text',
    fontSize: '2em',
    color: 'transparent',
    paddingBottom: '.25em',
    paddingTop: '.1em',
    filter: 'drop-shadow(0 0 .05rem black)',
    padding: '.05rem',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    WebkitBackgroundClip: 'text',
    WebkitTextStroke: '0.03em rgba(255, 255, 255, 0.6)',
  },
};
